on:
  push:
    # branches: [main]
    # paths: ["src/**"] # Trigger the action only when files change in the folders defined here
    paths: ["package.json"] # Trigger the action only when files change in the folders defined here
    tags:
      - "v*"
name: NPM Release
# jobs:
# publish:
#   runs-on: ubuntu-latest
#   permissions:
#     contents: read
#     packages: write
#   steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: 16.x
#         registry-url: https://registry.npmjs.org/
#     - run: npm install
#     - run: npm run build
#     - run: npm publish
#       env:
#         NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN}}
jobs:
  release:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: 1

      - name: Install Package dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTOMATION_TOKEN
          npm publish
        env:
          NPM_AUTOMATION_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
