name: Build and Deploy Storybook
on:
  push:
    branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Deploy
        run: |
          npm install
          npm run deploy-storybook -- --ci
        env:
          # GH_TOKEN: ${{ github.actor }}:${{ secrets.GH_TOKEN }}
          # username: ${{ github.actor }}
          # password: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
