# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    #     paths: ["stories/**", "src/components/**"] # Trigger the action only when files change in the folders defined here !!! but since our folder dir is diff we excluded
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: Install SSH Key
      #   uses: shimataro/ssh-key-action@v2
      #   with:
      #     key: ${{ secretes.SSH_PRIVATE_KEY }}
      #     known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - uses: actions/checkout@v2

      - name: Run a storybook deployer
        run: npm run deploy-storybook
        env:
          GH_TOKEN: Alchera:${{ secrets.GITHUB_TOKEN }}
